### ISSUE TITLE
Awesome library

### ISSUE THREAD

**Issue by shreyaspimpalgaonkar** [weavel-ai/Ape#2]
Hey, awesome work! Could you share the prompt that scored 93% on GSM8K? I think it would be useful for getting an intuition about the optimization algorithm and the output space. I went over the code briefly, but couldn't figure out the exact algorithm. 

Creating an issue as I couldn't find a discord link. Thanks!

**Comment by aschung01** [comment]
Thanks Shreyas! I'll add the jupyter notebooks for reproduce the results sometime today. You can also join our discord here: https://weavel.ai/discord :)
