### ISSUE TITLE
Pydantic Validation error for `EvaluationResult`

### ISSUE THREAD

**Issue by albertlieyingadrian** [weavel-ai/Ape#20]
Got an error cuz of the schema

```python
# https://github.com/weavel-ai/Ape/blob/e77f7bf15cdedfac6e74f21923d56f559dc9fc1e/ape/types/eval_result.py
class EvaluationResult(BaseModel):
    example: Union[dict, str]
    prediction: Union[dict, str]
    score: float
    intermediate_values: Optional[Dict[str, Any]] = None

```

<img width="836" alt="Screenshot 2024-09-22 at 1 19 58 AM" src="https://github.com/user-attachments/assets/d7f97ca8-7bda-4668-9e2a-92882a7f5de7">
<img width="609" alt="Screenshot 2024-09-22 at 1 20 08 AM" src="https://github.com/user-attachments/assets/ae11a629-97dc-431b-99e8-1cd9179f4a91">

**Comment by aschung01** [comment]
Thanks for reporting @albertlieyingadrian ! Just fixed this in PR #18
